/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Acciones.Conexion;
import Acciones.Operaciones;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.util.StringTokenizer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import javax.swing.event.AncestorListener;

/**
 *
 * @author MILTON
 */
public class AgregarLibros extends javax.swing.JFrame {
    Operaciones operaciones;    
    DefaultComboBoxModel modeloComboAutor = new DefaultComboBoxModel();
    DefaultComboBoxModel modeloComboIdioma = new DefaultComboBoxModel();
    String seleccionIdioma;
    String seleccionAutor;
    String textoPaginas;
    PrimerasPaginas pag ;
    ListarLibros listar;
    String copiar = "";
    File folder = new File("C:\\nuevaCarpeta");
    /**
     * Creates new form AgregarLibros
     */
    public AgregarLibros(){
        initComponents();
        pag = new PrimerasPaginas(this);
        operaciones = new Operaciones();
        operaciones.conectar();
        campo_reseña.setLineWrap(true); 
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension tamanio = tk.getScreenSize();
        this.setBounds(0, 0, tamanio.width, tamanio.height-40);
        operaciones.cargarAutores(modeloComboAutor);        
        operaciones.cargarIdioma(modeloComboIdioma);
        pag.setVisible(false);        
        if (!folder.exists())
            folder.mkdir();
        
    }

//    private AgregarLibros() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
    
        
    private void limpiar(){
        campo_titulo.setText("");        
        campo_paginas.setText("");
        campo_precio.setText("");        
        campo_Isbn.setText("");
        campo_fecha.setText("");
        campo_reseña.setText("");
        pag.setTexto("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CerrarSesion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Agregar = new javax.swing.JButton();
        primeras_pag = new javax.swing.JLabel();
        Idioma = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        campo_precio = new java.awt.TextField();
        Cant_pag = new javax.swing.JLabel();
        ComboAutor = new javax.swing.JComboBox();
        campo_paginas = new java.awt.TextField();
        Reseña = new javax.swing.JLabel();
        lanzamiento = new javax.swing.JLabel();
        campo_fecha = new javax.swing.JLabel();
        Autor = new javax.swing.JLabel();
        Titulo2 = new javax.swing.JLabel();
        AgregarPrimerasPaginas = new javax.swing.JButton();
        FechaLanzamiento = new javax.swing.JButton();
        campo_titulo = new java.awt.TextField();
        ComboIdioma = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        ImgLibro = new javax.swing.JLabel();
        BotonExaminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campo_reseña = new javax.swing.JTextArea();
        Isbn = new javax.swing.JLabel();
        campo_Isbn = new java.awt.TextField();
        AgregarAutor = new javax.swing.JButton();
        AgregarIdioma = new javax.swing.JButton();
        ImgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1360, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CerrarSesion.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        CerrarSesion.setText("Cerrar  Sesión");
        jPanel1.add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 30, 180, 40));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 32)); // NOI18N
        jLabel2.setText("Agregar nuevo libro");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cookbook2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 250, 110));

        atras.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        atras.setText("Atras");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 150));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agregar.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jPanel2.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 110, 30));

        primeras_pag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        primeras_pag.setText("Primeras paginas:");
        jPanel2.add(primeras_pag, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 30));

        Idioma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Idioma.setText("Idioma:");
        jPanel2.add(Idioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        precio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        precio.setText("Precio:");
        jPanel2.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));
        jPanel2.add(campo_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 130, 30));

        Cant_pag.setBackground(new java.awt.Color(255, 255, 255));
        Cant_pag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cant_pag.setText("Cantidad paginas:");
        jPanel2.add(Cant_pag, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 31));

        ComboAutor.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        ComboAutor.setModel(modeloComboAutor);
        ComboAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAutorActionPerformed(evt);
            }
        });
        jPanel2.add(ComboAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 210, 30));
        jPanel2.add(campo_paginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, 30));

        Reseña.setBackground(new java.awt.Color(255, 255, 255));
        Reseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Reseña.setText("Reseña:");
        jPanel2.add(Reseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 70, -1));

        lanzamiento.setBackground(new java.awt.Color(255, 255, 255));
        lanzamiento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lanzamiento.setText("Fecha de lanzamiento:");
        jPanel2.add(lanzamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, 30));

        campo_fecha.setBackground(new java.awt.Color(204, 204, 204));
        campo_fecha.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPanel2.add(campo_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 90, 30));

        Autor.setBackground(new java.awt.Color(255, 255, 255));
        Autor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Autor.setText("Autor:");
        jPanel2.add(Autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 30));

        Titulo2.setBackground(new java.awt.Color(255, 255, 255));
        Titulo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Titulo2.setText("Titulo:");
        jPanel2.add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        AgregarPrimerasPaginas.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        AgregarPrimerasPaginas.setText("Editar...");
        AgregarPrimerasPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPrimerasPaginasActionPerformed(evt);
            }
        });
        jPanel2.add(AgregarPrimerasPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 110, 30));

        FechaLanzamiento.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        FechaLanzamiento.setText("Fecha");
        FechaLanzamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaLanzamientoActionPerformed(evt);
            }
        });
        jPanel2.add(FechaLanzamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 90, 30));
        jPanel2.add(campo_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 320, 30));

        ComboIdioma.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        ComboIdioma.setModel(modeloComboIdioma);
        ComboIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboIdiomaActionPerformed(evt);
            }
        });
        jPanel2.add(ComboIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 200, 30));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 200, 210));

        BotonExaminar.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        BotonExaminar.setText("Examinar");
        BotonExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonExaminarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonExaminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        campo_reseña.setColumns(20);
        campo_reseña.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        campo_reseña.setRows(5);
        jScrollPane1.setViewportView(campo_reseña);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 300, 100));

        Isbn.setBackground(new java.awt.Color(255, 255, 255));
        Isbn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Isbn.setText("Isbn:");
        jPanel2.add(Isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 31));
        jPanel2.add(campo_Isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 120, 30));

        AgregarAutor.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        AgregarAutor.setText("Nuevo");
        AgregarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAutorActionPerformed(evt);
            }
        });
        jPanel2.add(AgregarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, 30));

        AgregarIdioma.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        AgregarIdioma.setText("Nuevo");
        AgregarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarIdiomaActionPerformed(evt);
            }
        });
        jPanel2.add(AgregarIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 630, 480));

        ImgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        ImgFondo.setText("Fondo");
        getContentPane().add(ImgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1360, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        String reseña = "";
        String line = new String(campo_reseña.getText());        
        StringTokenizer st = new StringTokenizer(line,"\n");                
        while (st.hasMoreTokens()){
            String pepe = st.nextToken();
            //System.out.println(pepe);
            reseña = ""+pepe;
        }   
        Libro libro; 
        //System.out.println(reseña);         
        try{
            float pre = Float.parseFloat(campo_precio.getText());
            int cantPag = Integer.parseInt(campo_paginas.getText());           
            int idAut = operaciones.buscoIdAutor(seleccionAutor);
            int idIdio = operaciones.buscoIdIdioma(seleccionIdioma);
            libro = new Libro(0,campo_Isbn.getText()
                ,campo_titulo.getText(),cantPag
                ,pre,campo_fecha.getText(),reseña
                ,pag.getTexto(),idAut,idIdio);
            operaciones.guardarLibro(libro);
            limpiar();

            //String destino = folder.getPath()+"\\"+libro.getTitulo()+".JPG"; // tiene que ser el ID del libro
            String destino = "//src//Imagenes//"+libro.getTitulo()+".JPG";
            File aCopiar = new File(copiar);
            File aDestino = new File(destino);
            FileChannel out;
            try (FileChannel in = (new FileInputStream(aCopiar)).getChannel()){
                out = (new FileOutputStream(aDestino)).getChannel();
            in.transferTo(0, aCopiar.length(), out);
            }catch(IOException e){
             JOptionPane.showMessageDialog(null,"Error al copiar imagen"); 
            }
            ImageIcon fot = new ImageIcon(destino);
            ImageIcon icono = new ImageIcon(fot.getImage().getScaledInstance(ImgLibro.getWidth(), ImgLibro.getHeight(), Image.SCALE_DEFAULT));
            ImgLibro.setIcon(icono);
            int opcion = JOptionPane.showConfirmDialog(null, "¿Desea agregar un nuevo libro?");
            if (opcion == JOptionPane.YES_OPTION){
                  this.dispose();
                  new AgregarLibros();
                  new ListarLibros();
            }
            else{
                this.dispose();
                new ListarLibros();}
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Por favor, complete todos los campos");
        }

                
    }//GEN-LAST:event_AgregarActionPerformed

    
    
    private void AgregarPrimerasPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPrimerasPaginasActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        pag.setVisible(true);                        
    }//GEN-LAST:event_AgregarPrimerasPaginasActionPerformed
     
    private void FechaLanzamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaLanzamientoActionPerformed
        // TODO add your handling code here:
     int año_malo = 0;
        String seleccion="";
        String comparacion = null;
        do{
           seleccion = JOptionPane.showInputDialog(null,"Escriba un año de publicación del libro");
           if (seleccion != comparacion)//&(Integer.parseInt(seleccion) != JOptionPane.CANCEL_OPTION))
                año_malo = Integer.parseInt(seleccion);
           else
               año_malo = 0;
           if ((año_malo <= 1600)&& (seleccion != null)) {
                 JOptionPane.showMessageDialog(null,"Ingreso un año inválido, vuelva a ingresarlo nuevamente");
            }
        }while ((año_malo < 1600) && (seleccion != null));
        if ((año_malo > 1600)&&(seleccion != comparacion)){
            DatePicker fecha = new DatePicker(Integer.parseInt(seleccion));
            String fecha_elegida;
             fecha_elegida = fecha.setPickedDate();       
            campo_fecha.setText(fecha_elegida);
        }
        
    }//GEN-LAST:event_FechaLanzamientoActionPerformed
    
    private void ComboIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboIdiomaActionPerformed
        // TODO add your handling code here:
        seleccionIdioma = (String)ComboIdioma.getSelectedItem();        
    }//GEN-LAST:event_ComboIdiomaActionPerformed

    private void BotonExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonExaminarActionPerformed
        // TODO add your handling code here:
         JFileChooser examinar = new JFileChooser();
          int resp = examinar.showOpenDialog(BotonExaminar);
          copiar = "";
          while (copiar.equals(""))
            copiar = examinar.getSelectedFile().toString();
          if (resp == JFileChooser.APPROVE_OPTION){
            ImgLibro.setSize(200, 210);
            ImgLibro.removeAll();
            ImageIcon fot = new ImageIcon(copiar);
            ImageIcon icono = new ImageIcon(fot.getImage().getScaledInstance(ImgLibro.getWidth(), ImgLibro.getHeight(), Image.SCALE_DEFAULT));
            ImgLibro.setIcon(icono);      
          }else{
              JOptionPane.showMessageDialog(null,"Cancelar");
          }
          
    }//GEN-LAST:event_BotonExaminarActionPerformed

    private void ComboAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAutorActionPerformed
        // TODO add your handling code here:
        seleccionAutor = (String)ComboAutor.getSelectedItem();                                              
    }//GEN-LAST:event_ComboAutorActionPerformed

    private void AgregarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAutorActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        AgregarAutorFrame nuevoAutor = new AgregarAutorFrame(this);
        nuevoAutor.setLocation(450, 100);
        nuevoAutor.setVisible(true);
        
    }//GEN-LAST:event_AgregarAutorActionPerformed

    private void AgregarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarIdiomaActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        agregarNuevoIdioma idioma = new agregarNuevoIdioma(this);
        idioma.setVisible(true);
    }//GEN-LAST:event_AgregarIdiomaActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        ListarLibros prueba = new ListarLibros();
        prueba.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_atrasActionPerformed
    
    /**
     * @param args the command line arguments
     */
 

    public String getTextoPaginas() {
        return textoPaginas;
    }

    public void setTextoPaginas(String textoPaginas) {
        this.textoPaginas = textoPaginas;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton AgregarAutor;
    private javax.swing.JButton AgregarIdioma;
    private javax.swing.JButton AgregarPrimerasPaginas;
    private javax.swing.JLabel Autor;
    private javax.swing.JButton BotonExaminar;
    private javax.swing.JLabel Cant_pag;
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JComboBox ComboAutor;
    private javax.swing.JComboBox ComboIdioma;
    private javax.swing.JButton FechaLanzamiento;
    private javax.swing.JLabel Idioma;
    private javax.swing.JLabel ImgFondo;
    private javax.swing.JLabel ImgLibro;
    private javax.swing.JLabel Isbn;
    private javax.swing.JLabel Reseña;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JButton atras;
    private java.awt.TextField campo_Isbn;
    private javax.swing.JLabel campo_fecha;
    private java.awt.TextField campo_paginas;
    private java.awt.TextField campo_precio;
    private javax.swing.JTextArea campo_reseña;
    private java.awt.TextField campo_titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lanzamiento;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel primeras_pag;
    // End of variables declaration//GEN-END:variables

    
}
