/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Acciones.Operaciones;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MILTON
 */
public class AgregarPaisDetalle extends javax.swing.JFrame {
    Operaciones operaciones;
    AgregarAutorDetalle autorFrame;
    /**
     * Creates new form AgregarPaisDetalle
     */
    public AgregarPaisDetalle(AgregarAutorDetalle nuevo) {
        initComponents();
        autorFrame = nuevo;
        operaciones = new Operaciones();
        operaciones.conectar();
        this.setLocation(450, 180);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         this.addWindowListener(new java.awt.event.WindowAdapter() { 
        public void windowClosing(java.awt.event.WindowEvent e) {	
            autorFrame.setEnabled(true);
            autorFrame.setVisible(true);
            dispose();
        }; 
        }); 
    }

    private AgregarPaisDetalle() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AgregarPais = new javax.swing.JButton();
        nombrePaisNuevo = new javax.swing.JLabel();
        campoNuevoPais = new java.awt.TextField();
        CancelarPais = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        AgregarPais.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        AgregarPais.setText("Agregar");
        AgregarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPaisActionPerformed(evt);
            }
        });

        nombrePaisNuevo.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        nombrePaisNuevo.setText("Pais:");

        campoNuevoPais.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N

        CancelarPais.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        CancelarPais.setText("Cancelar");
        CancelarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombrePaisNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNuevoPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 172, Short.MAX_VALUE)
                        .addComponent(AgregarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNuevoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombrePaisNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarPais)
                    .addComponent(CancelarPais))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPaisActionPerformed
        // TODO add your handling code here:
        if (!campoNuevoPais.getText().isEmpty()){
            operaciones.guardarPais(campoNuevoPais.getText());
            autorFrame.modeloComboPais.removeAllElements();
            autorFrame.operaciones.cargarPais(autorFrame.modeloComboPais);
            JOptionPane.showMessageDialog(null,"Se agrego nuevo pais");
           
            this.autorFrame.setEnabled(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Por favor ingrese un pais");
        }
    }//GEN-LAST:event_AgregarPaisActionPerformed

    private void CancelarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarPaisActionPerformed
        // TODO add your handling code here:this.autorFrame.setVisible(true);
            this.autorFrame.setEnabled(true); 
            this.autorFrame.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_CancelarPaisActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AgregarPaisDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AgregarPaisDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AgregarPaisDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AgregarPaisDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AgregarPaisDetalle().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarPais;
    private javax.swing.JButton CancelarPais;
    private java.awt.TextField campoNuevoPais;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombrePaisNuevo;
    // End of variables declaration//GEN-END:variables
}
