/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Acciones.Operaciones;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;
import java.nio.channels.FileChannel;
import java.util.LinkedList;
import java.util.StringTokenizer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Turqito
 */
public class DetalleLibro extends javax.swing.JFrame {

    Operaciones operaciones;    
    DefaultComboBoxModel modeloComboAutor = new DefaultComboBoxModel();
    DefaultComboBoxModel modeloComboIdioma = new DefaultComboBoxModel();
    String seleccionIdioma;
    String seleccionAutor;
    JTextArea textoPaginas;
    PrimerasPaginas pag;
    JTable tabla;
    private  Libro libro_detalle;
    int codigo;
    LinkedList<Libro> lista = new LinkedList<>();
    private final int fila;
    private int indice;
    File folder = new File("C:\\nuevaCarpeta");  
    String copiar;
    ListarLibros listarlibros;

    /**
     * Creates new form DetalleLibro
     */
    public DetalleLibro(Libro libro,int fila, JTable tabla, LinkedList<Libro> listaP, int index,final ListarLibros listarlibros) {
        initComponents();
        this.libro_detalle = libro;
        this.operaciones = new Operaciones();
        this.operaciones.conectar();
        this.operaciones.cargarAutores(modeloComboAutor);
        this.operaciones.cargarIdioma(modeloComboIdioma);
        this.setLocation(450, 180);
        this.setVisible(true);
        this.pag = new PrimerasPaginas(this);
        this.lista = listaP;
        this.fila = fila;
        this.tabla = tabla;
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.indice = index;
        this.pag.setVisible(false);
        this.listarlibros = listarlibros;
        this.addWindowListener(new java.awt.event.WindowAdapter() { 
        public void windowClosing(java.awt.event.WindowEvent e) {	
            listarlibros.setEnabled(true);
            listarlibros.setVisible(true);
            dispose();
        }; 
        }); 
        if (!folder.exists())
            folder.mkdir();
//       URL urlDeLaImagen = Autor.class.getClassLoader().getResource("\\Imagenes\\"+libro.getTitulo()+".JPG");
//       this.copiar = urlDeLaImagen.toString();
//       System.out.println(this.copiar);
//       ImageIcon icono = new ImageIcon(this.copiar);
        File archivo = new File (".\\src\\Imagenes\\"+libro.getTitulo()+".JPG");
        if (archivo.exists())
            this.copiar = ".\\src\\Imagenes\\"+libro.getTitulo()+".JPG";
        else
            this.copiar = "";
        this.completar(libro_detalle);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Modificar = new javax.swing.JButton();
        primeras_pag = new javax.swing.JLabel();
        Idioma = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        campo_precio = new java.awt.TextField();
        Cant_pag = new javax.swing.JLabel();
        ComboAutor = new javax.swing.JComboBox();
        campo_paginas = new java.awt.TextField();
        Reseña = new javax.swing.JLabel();
        lanzamiento = new javax.swing.JLabel();
        campo_fecha = new javax.swing.JLabel();
        Autor = new javax.swing.JLabel();
        Titulo2 = new javax.swing.JLabel();
        AgregarPrimerasPaginas = new javax.swing.JButton();
        NuevoAutor = new javax.swing.JButton();
        campo_titulo = new java.awt.TextField();
        ComboIdioma = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        ImgLibro = new javax.swing.JLabel();
        BotonExaminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campo_reseña = new javax.swing.JTextArea();
        Isbn = new javax.swing.JLabel();
        campo_Isbn = new java.awt.TextField();
        Eliminar = new javax.swing.JButton();
        NuevoIdioma = new javax.swing.JButton();
        FechaLanzamiento3 = new javax.swing.JButton();

        setTitle("CookBook - Detalle del libro");
        setAutoRequestFocus(false);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Modificar.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel2.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 110, 30));

        primeras_pag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        primeras_pag.setText("Primeras paginas:");
        jPanel2.add(primeras_pag, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 30));

        Idioma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Idioma.setText("Idioma:");
        jPanel2.add(Idioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        precio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        precio.setText("Precio:");
        jPanel2.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));
        jPanel2.add(campo_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 130, 30));

        Cant_pag.setBackground(new java.awt.Color(255, 255, 255));
        Cant_pag.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cant_pag.setText("Cantidad paginas:");
        jPanel2.add(Cant_pag, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 31));

        ComboAutor.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        ComboAutor.setModel(modeloComboAutor);
        ComboAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAutorActionPerformed(evt);
            }
        });
        jPanel2.add(ComboAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 210, 30));
        jPanel2.add(campo_paginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, 30));

        Reseña.setBackground(new java.awt.Color(255, 255, 255));
        Reseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Reseña.setText("Reseña:");
        jPanel2.add(Reseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 70, -1));

        lanzamiento.setBackground(new java.awt.Color(255, 255, 255));
        lanzamiento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lanzamiento.setText("Fecha de lanzamiento:");
        jPanel2.add(lanzamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, 30));

        campo_fecha.setBackground(new java.awt.Color(204, 204, 204));
        campo_fecha.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPanel2.add(campo_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 90, 30));

        Autor.setBackground(new java.awt.Color(255, 255, 255));
        Autor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Autor.setText("Autor:");
        jPanel2.add(Autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 30));

        Titulo2.setBackground(new java.awt.Color(255, 255, 255));
        Titulo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Titulo2.setText("Titulo:");
        jPanel2.add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        AgregarPrimerasPaginas.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        AgregarPrimerasPaginas.setText("Editar...");
        AgregarPrimerasPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPrimerasPaginasActionPerformed(evt);
            }
        });
        jPanel2.add(AgregarPrimerasPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 110, 30));

        NuevoAutor.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        NuevoAutor.setText("Nuevo");
        NuevoAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoAutorActionPerformed(evt);
            }
        });
        jPanel2.add(NuevoAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 90, 30));
        jPanel2.add(campo_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 320, 30));

        ComboIdioma.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        ComboIdioma.setModel(modeloComboIdioma);
        ComboIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboIdiomaActionPerformed(evt);
            }
        });
        jPanel2.add(ComboIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 200, 30));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 200, 210));

        BotonExaminar.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        BotonExaminar.setText("Examinar");
        BotonExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonExaminarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonExaminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        campo_reseña.setColumns(20);
        campo_reseña.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        campo_reseña.setRows(5);
        jScrollPane1.setViewportView(campo_reseña);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 300, 100));

        Isbn.setBackground(new java.awt.Color(255, 255, 255));
        Isbn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Isbn.setText("Isbn:");
        jPanel2.add(Isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 31));
        jPanel2.add(campo_Isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 120, 30));

        Eliminar.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel2.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 110, 30));

        NuevoIdioma.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        NuevoIdioma.setText("Nuevo");
        NuevoIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoIdiomaActionPerformed(evt);
            }
        });
        jPanel2.add(NuevoIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 90, 30));

        FechaLanzamiento3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        FechaLanzamiento3.setText("Fecha");
        FechaLanzamiento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaLanzamiento3ActionPerformed(evt);
            }
        });
        jPanel2.add(FechaLanzamiento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        String reseña = "";
        Libro libro = null;
        String line = new String(campo_reseña.getText());
        StringTokenizer st = new StringTokenizer(line,"\n");
        while (st.hasMoreTokens()){
            String pepe = st.nextToken();
            reseña = ""+pepe;
        }
        try{
            float pre = Float.parseFloat(campo_precio.getText());
            int cantPag = Integer.parseInt(campo_paginas.getText());
            int idAut = operaciones.buscoIdAutor(seleccionAutor);
            int idIdio = operaciones.buscoIdIdioma(seleccionIdioma);
            libro = new Libro(this.libro_detalle.getId(),
                    campo_Isbn.getText(),
                    campo_titulo.getText(),
                    cantPag,
                    pre,
                    campo_fecha.getText(),
                    reseña,
                    pag.getTexto(),
                    idAut,
                    idIdio);   
            //System.out.print("estamos por copiar la nueva imagen");
            
            //String destino = folder.getPath()+"\\"+libro.getTitulo()+".JPG"; // tiene que ser el ID del libro
            String destino = ".\\src\\Imagenes\\"+libro.getTitulo()+".JPG";
            if (!copiar.equals(destino)){// tiene que ser el ID del libro
            //System.out.print("Empezamos a copiar "+copiar+" a este lugar "+destino);
            File aCopiar = new File(copiar);
            File aDestino = new File(destino);
            FileChannel out;
            try (FileChannel in = (new FileInputStream(aCopiar)).getChannel()){
                out = (new FileOutputStream(aDestino)).getChannel();
            in.transferTo(0, aCopiar.length(), out);
            
            }catch(IOException e){
             JOptionPane.showMessageDialog(null,"Error al copiar imagen"); 
            }            
            }

            ImageIcon fot = new ImageIcon(destino);
            ImageIcon icono = new ImageIcon(fot.getImage().getScaledInstance(ImgLibro.getWidth(), ImgLibro.getHeight(), Image.SCALE_DEFAULT));
            ImgLibro.setIcon(icono);
            copiar ="";

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Por favor, complete todos los campos");
        }   
            operaciones.modificarLibro(libro);
            this.lista.remove(indice);
            this.lista.add(libro);
             Object[] datos_fila ={
                        this.lista.getLast().getTitulo(),
                        this.operaciones.buscoNombreAutor(this.lista.getLast().getAutor_id()),
                        this.lista.getLast().getPrecio()
                      };
                      DefaultTableModel modeloDeLaTabla=(DefaultTableModel)tabla.getModel();
                      modeloDeLaTabla.removeRow(fila);
                      modeloDeLaTabla.addRow(datos_fila);
                      tabla.setModel(modeloDeLaTabla);
                      this.setVisible(false);
                      this.listarlibros.setEnabled(true);
                      this.listarlibros.setVisible(true);


    }//GEN-LAST:event_ModificarActionPerformed
           
    private int indiceCombo (DefaultComboBoxModel modelo, String aBuscar){
        boolean encontre = false;
        int i;
        for (i=0;i < modelo.getSize(); i++){
            if (modelo.getElementAt(i).equals(aBuscar)){
                encontre = true;
                //System.out.print("DIO IGUAL"+aBuscar);
                break;
            }
        }
        if (encontre)
            return i;
        else 
            return -1;
    }
    
    private void completar(Libro libro){
        campo_titulo.setText(libro.getTitulo());        
        campo_paginas.setText(Integer.toString(libro.getCant_paginas()));
        campo_precio.setText(Float.toString(libro.getPrecio()));
        int indiceAutor = indiceCombo(modeloComboAutor, this.operaciones.buscoNombreAutor(libro.getAutor_id()));
        int indiceIdioma = indiceCombo(modeloComboIdioma, this.operaciones.buscoIdioma(libro.getIdioma_id()));
        if (indiceAutor > 0)
            ComboAutor.setSelectedIndex(indiceAutor);
        if (indiceIdioma > 0)
            ComboIdioma.setSelectedIndex(indiceIdioma);
        campo_Isbn.setText(libro.getIsbn());
        campo_fecha.setText(libro.getFecha_lanzamiento());
        campo_reseña.setText(libro.getResumen());
        pag.getCampo_primerasPaginas().setText(libro.getPrimeras_paginas());
        if (!copiar.equals("")){
            ImageIcon fot = new ImageIcon(copiar);
            ImageIcon icono = new ImageIcon(fot.getImage().getScaledInstance(ImgLibro.getWidth(), ImgLibro.getHeight(), Image.SCALE_DEFAULT));
            ImgLibro.setIcon(icono);
        }
      
    }
    
    private void ComboAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAutorActionPerformed
        // TODO add your handling code here:
        seleccionAutor = (String)ComboAutor.getSelectedItem();
        //System.out.println(seleccionAutor);
    }//GEN-LAST:event_ComboAutorActionPerformed

    private void AgregarPrimerasPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPrimerasPaginasActionPerformed
        // TODO add your handling code here:
       
        this.setEnabled(false);
        pag.setVisible(true);
    }//GEN-LAST:event_AgregarPrimerasPaginasActionPerformed

    private void NuevoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoAutorActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        AgregarAutorDetalle nuevoAutor = new AgregarAutorDetalle(this);
        nuevoAutor.setLocation(450, 100);
        nuevoAutor.setVisible(true);
    }//GEN-LAST:event_NuevoAutorActionPerformed

    private void ComboIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboIdiomaActionPerformed
        // TODO add your handling code here:
        seleccionIdioma = (String)ComboIdioma.getSelectedItem();
        //System.out.println(seleccionIdioma);
    }//GEN-LAST:event_ComboIdiomaActionPerformed

    private void BotonExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonExaminarActionPerformed
        // TODO add your handling code here:
          JFileChooser examinar = new JFileChooser();
          int resp = examinar.showOpenDialog(BotonExaminar);
          String aCopiar;
          aCopiar = "";
          if (resp == JFileChooser.APPROVE_OPTION){
            aCopiar = examinar.getSelectedFile().toString();
            ImgLibro.setSize(200, 210);
            ImgLibro.removeAll();
            ImageIcon fot = new ImageIcon(aCopiar);
            ImageIcon icono = new ImageIcon(fot.getImage().getScaledInstance(ImgLibro.getWidth(), ImgLibro.getHeight(), Image.SCALE_DEFAULT));
            ImgLibro.setIcon(icono);
          }
            //          }/*else{
            //              JOptionPane.showMessageDialog(null,"Cancelar");
            //          }*/

    }//GEN-LAST:event_BotonExaminarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        int confirmado = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar el libro '"+this.libro_detalle.getTitulo()+"'?");
        if (JOptionPane.YES_OPTION == confirmado){
            this.operaciones.eliminarLibro(this.libro_detalle.getId());
            DefaultTableModel temp = (DefaultTableModel) tabla.getModel();
            temp.removeRow(fila);
            this.lista.remove(indice);
            File aBorrar = new File (copiar);
            if (aBorrar.exists()){
                aBorrar.delete();
            }
            this.setVisible(false);
            this.dispose();
            this.listarlibros.setEnabled(true);
            this.listarlibros.setVisible(true);
        }            
    }//GEN-LAST:event_EliminarActionPerformed

    private void NuevoIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoIdiomaActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        agregarIdiomaDetalle idioma = new agregarIdiomaDetalle(this);
        idioma.setVisible(true);
    }//GEN-LAST:event_NuevoIdiomaActionPerformed

    private void FechaLanzamiento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaLanzamiento3ActionPerformed
        // TODO add your handling code here:
        int año_malo = 0;
        String seleccion="";
        String comparacion = null;
        do{
           seleccion = JOptionPane.showInputDialog(null,"Escriba un año de publicación del libro");
           if (seleccion != comparacion)//&(Integer.parseInt(seleccion) != JOptionPane.CANCEL_OPTION))
                año_malo = Integer.parseInt(seleccion);
           else
               año_malo = 0;
           if ((año_malo <= 1600)&& (seleccion != null)) {
                 JOptionPane.showMessageDialog(null,"Ingreso un año inválido, vuelva a ingresarlo nuevamente");
            }
        }while ((año_malo < 1600) && (seleccion != null));
        if ((año_malo > 1600)&&(seleccion != comparacion)){
            DatePicker fecha = new DatePicker(Integer.parseInt(seleccion));
            String fecha_elegida;
             fecha_elegida = fecha.setPickedDate();       
            campo_fecha.setText(fecha_elegida);
        }
    }//GEN-LAST:event_FechaLanzamiento3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarPrimerasPaginas;
    private javax.swing.JLabel Autor;
    private javax.swing.JButton BotonExaminar;
    private javax.swing.JLabel Cant_pag;
    private javax.swing.JComboBox ComboAutor;
    private javax.swing.JComboBox ComboIdioma;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton FechaLanzamiento3;
    private javax.swing.JLabel Idioma;
    private javax.swing.JLabel ImgLibro;
    private javax.swing.JLabel Isbn;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton NuevoAutor;
    private javax.swing.JButton NuevoIdioma;
    private javax.swing.JLabel Reseña;
    private javax.swing.JLabel Titulo2;
    private java.awt.TextField campo_Isbn;
    private javax.swing.JLabel campo_fecha;
    private java.awt.TextField campo_paginas;
    private java.awt.TextField campo_precio;
    private javax.swing.JTextArea campo_reseña;
    private java.awt.TextField campo_titulo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lanzamiento;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel primeras_pag;
    // End of variables declaration//GEN-END:variables
}
