/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.StringTokenizer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JScrollBar;
import javax.swing.JTextArea;

/**
 *
 * @author MILTON
 */
public class PrimerasPaginas extends javax.swing.JFrame {
    /**
     * Creates new form PrimerasPaginas
     */
    
    String texto = "";
    AgregarLibros framePrimerasP = null;
    public PrimerasPaginas(AgregarLibros agregarLibro){
        initComponents();
        campo_primerasPaginas.setLineWrap(true); 
        this.setLocation(450, 180);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        framePrimerasP = agregarLibro;
        this.addWindowListener(new java.awt.event.WindowAdapter() { 
        public void windowClosing(java.awt.event.WindowEvent e) {	
            framePrimerasP.setEnabled(true);
            framePrimerasP.setVisible(true);
            dispose();
        }; 
        }); 
    }
    
    public PrimerasPaginas (){
        
    }
    DetalleLibro frameDetalle = null;
    
    public PrimerasPaginas(DetalleLibro detalle) {
    initComponents();
        campo_primerasPaginas.setLineWrap(true); 
        this.setLocation(450, 180);
        this.frameDetalle = detalle;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() { 
        public void windowClosing(java.awt.event.WindowEvent e) {	
            frameDetalle.setEnabled(true);
            frameDetalle.setVisible(true);
            dispose();
        }; 
        }); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campo_primerasPaginas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        AceptarPaginas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        campo_primerasPaginas.setColumns(20);
        campo_primerasPaginas.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        campo_primerasPaginas.setRows(5);
        jScrollPane1.setViewportView(campo_primerasPaginas);
        campo_primerasPaginas.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel1.setText("Agregar primeras paginas...");

        AceptarPaginas.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        AceptarPaginas.setText("Aceptar");
        AceptarPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarPaginasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AceptarPaginas)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AceptarPaginas)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getTexto() {
        return texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
        campo_primerasPaginas.setText("");
    }
     
    
    private void AceptarPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarPaginasActionPerformed
        // TODO add your handling code here:        
        String line = new String(campo_primerasPaginas.getText());        
        StringTokenizer st = new StringTokenizer(line,"\n");                
        while (st.hasMoreTokens()){
            String pepe = st.nextToken();
            //System.out.println(pepe);
            texto = ""+pepe;
        }           
        //System.out.println(texto);
        if (!line.isEmpty()){
            JOptionPane.showMessageDialog(null,"Se cargaron las primeras paginas de forma correcta");            
        }else{
            JOptionPane.showMessageDialog(null,"No se cargo ninguna información");
        }       
        if (frameDetalle == null){
            framePrimerasP.setEnabled(true);
            framePrimerasP.setVisible(true);
        }
        else
            if (framePrimerasP == null){
                frameDetalle.setEnabled(true);
                frameDetalle.setVisible(true);
            }
        this.setVisible(false);   
        
        
    }//GEN-LAST:event_AceptarPaginasActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PrimerasPaginas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PrimerasPaginas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PrimerasPaginas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PrimerasPaginas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new PrimerasPaginas().setVisible(true);
//            }
//        });
//    }

    public JTextArea getCampo_primerasPaginas() {
        return campo_primerasPaginas;
    }

    public void setCampo_primerasPaginas(JTextArea campo_primerasPaginas) {
        this.campo_primerasPaginas = campo_primerasPaginas;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarPaginas;
    private javax.swing.JTextArea campo_primerasPaginas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

 


}
